name: DWD Radolan Harvester Unified

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (e.g. development or production)"
        required: true
        type: string
      dwd_harvester_version:
        description: "Version of the DWD Harvester Docker Image"
        required: true
        type: string
  repository_dispatch:
    types: [radolan_cron]

jobs:
  rain:
    runs-on: ubuntu-latest
    name: Aggregate rain data from DWD radolan
    steps:
      - name: Set Up Variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment || github.event.client_payload.environment || 'development' }}" >> $GITHUB_ENV
          echo "DWD_VERSION=${{ github.event.inputs.dwd_harvester_version || github.event.client_payload.dwd_version || 'latest' }}" >> $GITHUB_ENV
        id: setup-variables
      - name: Should be the Harvester
        run: echo "$DWD_VERSION in $ENVIRONMENT"
        id: harvester

